/**
 * @file locking_table.h
 *
 * @brief This is generated by locking_generator.py
 *
 * Copyright (c) 2022 Laird Connectivity
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __LOCKING_TABLE_H__
#define __LOCKING_TABLE_H__

/******************************************************************************/
/* Includes                                                                   */
/******************************************************************************/
#include <zephyr.h>
#include <zephyr/types.h>
#include <stddef.h>

#include "locking_defs.h"

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************/
/* Indices                                                                    */
/******************************************************************************/

/* pystart - locking ids */
#define LOCKING_ID_adc                                0
/* pyend */

/******************************************************************************/
/* Constants and Enumerations                                                 */
/******************************************************************************/

/* pystart - locking constants */
#define LOCKING_TABLE_SIZE              1
#define LOCKING_TABLE_MAX_ID            0
/* pyend */

#ifdef __cplusplus
}
#endif

#endif /* __LOCKING_TABLE_H__ */
